### ISSUE TITLE
May you help me set up your library?

### ISSUE THREAD

**Issue by DmytroTols** [bobwolff68/LVGLPlusPlus#2]
I'm trying to implement your library into my Eclipse project and I continue to get different errors, all i did was #include "lvgl++/src/lvpp.h" and I started getting error like error: 'assert' was not declared in this scope in lvppBase.h when calling assert(!cbOnValueChanged), i fixed this issue and then i got lvgl/src/misc/lv_color.h:234:45: error: expected initializer before 'lv_color_int_t', do i do something wrong?

**Comment by bobwolff68** [comment]
Hey there - I haven't tried using an Eclipse project for this library. It shouldn't make some big difference, but sometimes the underlying toolchain that tools use can trip things up. I suspect that's the case here. 

Assert is a pretty common thing but it could be nullified by a `#define assert` but it sounds like you nailed that one.

The item around lv_color_int_t is interesting and makes me wonder if you've got a troubled compiler. Doing a quick 'grep' in the lvgl sources (not my C++ wrapper but the base library), I see:

`docs/overview/color.md:- `lv_color_int_t` `uint8_t`, `uint16_t` or `uint32_t` depending on the color depth setting. Used to build color arrays from plain numbers.
src/misc/lv_color.h:typedef LV_CONCAT3(uint, LV_COLOR_SIZE, _t) lv_color_int_t;`

In lv_color.h they define a typedef of lv_color_int_t based upon a creative concatenation of "uint" and the LV_COLOR_SIZE and "_t" to create uint8_t or uint16_t etc. It's unclear from the error if it's having trouble doing the LV_CONCAT3() or if maybe LV_COLOR_SIZE isn't defined? This should be defined in your lvgl_conf.h file.

Have you tried compiling either of the sample projects - threaded or unthreaded? I'd suggest that might be an excellent place to start to gain some sanity and success. Since the project is already a known quantity, you can rule out missing files like lvgl_conf.h and such. 

My other thought would be to consider using VSCode instead of Eclipse. Is there a particular reason you're using Eclipse? 

Thanks!
bob

**Comment by DmytroTols** [comment]
Eclipse in indeed very problematical tool, but unfortunately that's the only tool which I allowed to use for my devices, I tried running your demo projects but for some reason Eclipse won't read them, it's not allowing me to do anything with them. But what I see is that if i have just lvgl it won't compile, so it's not your library error, but lvgl itself, thanks for your time, I won't close this issue for now, so that if i find solution i can leave it here..maybe will be helpful for someone in future

**Comment by bobwolff68** [comment]
Ahh, bummer you don't have many choices.  I'd suggest the forum.lvgl.io for searching for eclipse support. Also our may be contorted, but you could build lvglplusplus into a library file and then just add it to your eclipse project as a link item?

**Comment by bobwolff68** [comment]
Great to hear. And thanks for following up with your solution.
